- id: p6
  unique-name: '2605-peru-project'
  name: "La Margarita / 3 Roasters Project"
  #price: 13
  grammage: 50
  release: "June 2026"
  details: "I proudly present the 3 roaster's interpretation of one green project. Apart from me, JayC and Harest are roasting. The coffee will be available on brup's webshop Bean Bodega."
  origin: Peru
  variety: Gesha
  process: Natural
  tasting_notes: Mango, jasmine, blackberry
  farmer: Solorzano Family

- id: p2
  unique-name: '2505-campohermoso-gesha-honey'
  name: "Campo Hermoso Gesha"
  price: 18.50
  grammage: 100
  release: "May 2025"
  details: "Campo Hermoso is a famous and very progressive farm in Colombia.\nThis coffee was the best on the cupping table amongst five different coffees that I sourced from Columbian Spirit."
  fob: 46.7
  origin: Colombia
  variety: Gesha
  process: Honey
  tasting_notes: Pineapple, rose, lemongrass
  altitude: 1750
  cupping_score: 88+
  region: Quindio
  farmer: Edwin Norena
  farm: Campo Hermoso

- id: p3
  unique-name: '2511-gloria-natural'
  name: "Gloria Natural"
  price: 8.50
  grammage: 100
  release: "November 2025"
  details: "First direct trade Kenyan that I have seen in my coffee career. A friend and coffee nerd suggested this coffee as one of his favorites back in 2024. Fortunately, shokunin got the greens this year too."
  fob: 18.25
  origin: Kenya
  variety: SL28
  process: Natural
  tasting_notes: Black currant, wine gum, rose
  altitude: 1800
  region: Nabiswa
  farmer: Gloria and Jarmo Gummerus
  farm: Sakami Coffee
  
- id: p4
  unique-name: '2511-caravela-sidra'
  name: "Caravela Sidra"
  price: 12
  grammage: 100
  release: "November 2025"
  details: "I had this when it released in Tallin at surfcafé. They provide such a nice experience there and are really close with Jelle from shokunin, plus the baristas travel to origin!"
  fob: 28.43
  origin: Ecuador
  variety: Sidra
  process: Washed
  tasting_notes: Raspberry, elderflower, earl grey tea
  altitude: 1350
  region: Pichincha
  farmer: Caravela organization with Fausto Romo and Marco Morocho

  farm: La Carolina, La Fortaleza
  
- id: p5
  unique-name: '2605-aragash-gelcha'
  name: "Aragash Gelcha"
  price: 13
  grammage: 100
  release: "May 2026"
  details: "Natural ethiopians are usually not my thing with their often outstanding strawberry note. This however has a clean blackberry which I love. This coffee was part of my test of a new importer and so far these coffees have not disappointed. Together with my beloved MCL coffee nerds we cupped these at our meetup."
  fob: 32.22
  origin: Ethiopia
  variety: 74110, Kurume
  process: Natural
  tasting_notes: Blackberry, black tea, coconut
  altitude: 2150
  region: Gedeb, Gedio
  farmer: Smallholders
  
- id: p7
  unique-name: '2605-paraiso-caturra'
  name: "El Paraiso Caturra"
  price: 21.5
  grammage: 100
  release: "May 2026"
  details: "Habanero note: If you know, you know. It is very green tasting and I love it. This coffee was part of my test of a new importer and so far these coffees have not disappointed. Together with my beloved MCL coffee nerds we cupped these at our meetup."
  fob: 52.62
  origin: Colombia
  variety: Caturra
  process: Washed, experimental
  tasting_notes: Guave, hops, violet, habanero
  altitude: 1950
  region: Piendamo, Cauca
  farmer: Wilton Benitez
  farm: Finca El Paraiso
    
- id: p8
  unique-name: '2605-paraiso-castillo'
  name: "El Paraiso Castillo"
  price: 16.5
  grammage: 100
  release: "May 2026"
  details: "Clean and nice. This coffee was part of my test of a new importer and so far these coffees have not disappointed. Together with my beloved MCL coffee nerds we cupped these at our meetup."
  fob: 39.02
  origin: Colombia
  variety: Caturra
  process: Washed, advanced
  tasting_notes: Haribos, milk chocolate, lime
  altitude: 1950
  region: Piendamo, Cauca
  farmer: Wilton Benitez
  farm: Finca El Paraiso
      
- id: p9
  unique-name: '2605-plan-libertat'
  name: "Plan Libertat"
  price: 16
  grammage: 100
  release: "May 2026"
  details: "Some nice yellow taste, hmm. This coffee was part of my test of a new importer and so far these coffees have not disappointed. Together with my beloved MCL coffee nerds we cupped these at our meetup."
  fob: 39.02
  origin: Mexico
  variety: Maragogype
  process: Washed
  tasting_notes: Stone fruit, mango, citrus
  altitude: 1700
  region: Chiapas
  farmer: Don Ezequiel Diaz
  
- id: e0
  unique-name: '2511-abaca-red-01'
  name: "Abaca reds"
  price: 6
  details: "100 Abaca red filters, size 01"


