- id: p0
  unique-name: '2501-gloria-washed'
  name: "Gloria Washed" 
  price: 11.90
  grammage: 125 # link to the product directory (with images and product page)
  release: "Jan 2025"
  details: "Detailed description."
  origin: Kenya
  variety: SL28
  process: Washed
  tasting_notes: Red berries, cacao nibs, orange blossom, nuts
- id: p1
  unique-name: '2501-gloria-natural'
  name: "Gloria Natural"
  price: 11.90
  grammage: 125
  release: "Jan 2025"
  details: "Detailed description."
- id: p2
  unique-name: '2501-p2-process'
  name: "Product 2"
  price: 9.90
  grammage: 125
  release: "Jan 2025"
  details: "Detailed description."