- id: p99
  unique-name: '2401-gloria-washed'
  name: "Gloria Washed"
  price: 19.90 
  grammage: 125    # link to the product directory (with images and product page)
  release: "Jan 2024"
- id: p98
  unique-name: '2401-gloria-natural'
  name: "Gloria Natural"
  price: 19.90
  grammage: 125
  release: "Jan 2024"
- id: p97
  unique-name: '2401-p2-process'
  name: "Product 2"
  price: 13.30
  grammage: 125
  release: "Jan 2024"