- id: p0
  name: "Gloria Washed"
  price: 19.90
  link: "/products/product0/product0.html"      # link to the product directory (with images and product page)
  image: "/products/product0/image0.jpg"
- id: p1
  name: "Gloria Natural"
  price: 19.90
  link: "/products/product1/product1.html"
  image: "/products/product1/image1.jpg"
- id: p2
  name: "Product 2"
  price: 13.30
  link: "/products/product2/product2.html"
  image: "/products/product2/image2.jpg"