# Personal Brew Coffee homepage config
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Personal Brew Coffee
description: Light roasted exquisite beans for your daily filter brew.
